name: Snapshot

on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  call-tool-snapshot:
    name: 🏭
    uses: cip4/.github/.github/workflows/tool-snapshot.yml@master
    with:
      confluence-label: bambi
      confluence-content-id: 1457553964
      apple-bundle-id: org.cip4.bambi
      docker-build: true
      java-version: 17
      java-distribution: 'temurin'
    secrets: inherit