name: Bambi Snapshot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macosx-snapshot:
    runs-on: macos-latest
    steps:
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew createDmg

      - name: Upload MacOSX App
        uses: actions/upload-artifact@v1
        with:
          name: macosx app file
          path: build/distributions/Bambi-development.dmg

      - name: Upload JAR
        uses: actions/upload-artifact@v1
        with:
          name: jar file
          path: build/libs/Bambi-development.jar

  windows-snapshot:
    runs-on: windows-latest
    steps:
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew createExe

      - name: Upload EXE
        uses: actions/upload-artifact@v1
        with:
          name: exe file
          path: build/launch4j/Bambi.exe