name: Snapshot

on:
  workflow_dispatch:
  push:
    branches: [ main, IN-400 ]
jobs:
  call-tool-snapshot:
    name: 🏭
    uses: cip4/.github/.github/workflows/tool-snapshot.yml@docker
    with:
      confluence-label: bambi
      confluence-content-id: 1457553964
      apple-bundle-id: org.cip4.bambi
      docker-build: true
    secrets:
      APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
      APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
      APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      ATLASSIAN_USER: ${{ secrets.ATLASSIAN_USER }}
      ATLASSIAN_TOKEN: ${{ secrets.ATLASSIAN_TOKEN }}
      GCP_SA_KEY:  ${{ secrets.GCP_SA_KEY }}
      GCP_PROJECT_ID:  ${{ secrets.GCP_PROJECT_ID }}
      DOCKER_HUB_USERNAME:  ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD:  ${{ secrets.DOCKER_HUB_PASSWORD }}