name: Snapshot

on:
  schedule:
    - cron:  '0 3 * * *'
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: europe-west1
  SERVICE_NAME: bambi-cip4-org

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup GCloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '298.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build docker container
        run: |-
          docker build \
            -t "docker.pkg.github.com/cip4/bambi/bambi:latest" \
            -t "gcr.io/$PROJECT_ID/$SERVICE_NAME:latest" \
            --build-arg VERSION=dev \
            --build-arg BUILD_NUMBER=${GITHUB_RUN_NUMBER} \
            --build-arg GIT_REV=${GITHUB_SHA} \
            .

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker container to pkg.github.om
        run: docker push docker.pkg.github.com/cip4/bambi/bambi:latest

      - name: Docker Auth GCloud
        run: gcloud auth configure-docker

      - name: Push Image to Google Container Registry
        run: docker push "gcr.io/$PROJECT_ID/$SERVICE_NAME:latest"

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy "$SERVICE_NAME" \
            --region "$RUN_REGION" \
            --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:latest" \
            --platform "managed" \
            --allow-unauthenticated

  macos-build:
    runs-on: macos-latest
    steps:
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew createDmg

      - name: Upload MacOS App
        uses: actions/upload-artifact@v1
        with:
          name: macosx app file
          path: build/distributions/Bambi-development.dmg

      - name: Upload JAR
        uses: actions/upload-artifact@v1
        with:
          name: jar file
          path: build/libs/Bambi-development.jar

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew createExe

      - name: Debug
        run: ls -l build/launch4j

      - name: Upload EXE
        uses: actions/upload-artifact@v1
        with:
          name: exe file
          path: build/launch4j/Bambi-development.exe
