name: Snapshot

on:
  push:
    branches: [ master ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build docker container
        run: docker build -t docker.pkg.github.com/cip4/bambi/bambi:latest .

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Push docker container
        run: docker push docker.pkg.github.com/cip4/bambi/bambi:latest

  macosx-build:
    runs-on: macos-latest
    steps:
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew createDmg

      - name: Upload MacOSX App
        uses: actions/upload-artifact@v1
        with:
          name: macosx app file
          path: build/distributions/Bambi-development.dmg

      - name: Upload JAR
        uses: actions/upload-artifact@v1
        with:
          name: jar file
          path: build/libs/Bambi-development.jar

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew createExe

      - name: Debug
        run: ls -l build/launch4j

      - name: Upload EXE
        uses: actions/upload-artifact@v1
        with:
          name: exe file
          path: build/launch4j/Bambi-development.exe